### ISSUE TITLE
Create reference for calculating

### ISSUE THREAD

**Issue by ArtemSherenkovskiy** [ArtemSherenkovskiy/utilities#4]
Ссылочка, запускает функцию before_calculate_layout или что то такое

Так же создать две view, одна 1) before_calculate_view.blade.php и вторая 2) after_calculate_view.blade.php 
Названия могут варьироваться 
1) имеет 2 кнопки для сброса в изначальное положение и для вызова функции calculate
В параметр передается request
2) имеет одну кнопку, сохранить в истории (вызов функции save_history, принимает параметр request) и типа сообщить об ошибке, или может не иметь кнопок вообще, а сохранение в истории проводится автоматически, это надо еще уточнить... но пока лучше так, потому что пользователь, может не заплатить полную стоимость и типа в истории будет храниться дичь...

**Comment by ArtemSherenkovskiy** [comment]
Также обе имеют поле content куда будет передаваться код из функций

**Comment by ArtemSherenkovskiy** [comment]
Выдачей сначала мою ветку, у меня там могут быть задатки вьюшек

**Comment by ArtemSherenkovskiy** [comment]
Кнопка на view, на котором отображается резльтат исчеслений, должна в итоге вызывать функцию save_history($request)

**Comment by ArtemSherenkovskiy** [comment]
функция save_history($request) ничего не возвращает
можно либо возвращаться на стартовый экран, либо выдавать страницу с надписью "Ваши покания успешно сохранены"

**Comment by bartonu4** [comment]
добавлено, когда сохраняешь показывает 2 сек "успешно сохранено" и редиректит к сервисам
