### ISSUE TITLE
create message view

### ISSUE THREAD

**Issue by ArtemSherenkovskiy** [ArtemSherenkovskiy/utilities#6]
короче надо создать view  в котором будет выдаваться сообщение об ошибке
то есть это просто какая то страница, с переменной  $message(хранит только само сообщение без тегов и чего либо еще), которая вставленная внутрь всех необхоимых тегов. Вызывающий сам подставляет переменную типа string  на место $message

**Comment by bartonu4** [comment]
добавлено view  'errors/message'
