### ISSUE TITLE
calculate и history 

### ISSUE THREAD

**Issue by bartonu4** [ArtemSherenkovskiy/utilities#7]
Когда один раз сохраняешь в истории  нельзя опять нажать рассчитать

![image](https://cloud.githubusercontent.com/assets/10919969/12245425/0d313996-b8b1-11e5-84e2-073ae8729be2.png)

**Comment by ArtemSherenkovskiy** [comment]
Ну так в теории ж правильно, ведь ты рассчет за этот месяц провел уже...

**Comment by ArtemSherenkovskiy** [comment]
Дичь какая то с тайм периодом

**Comment by ArtemSherenkovskiy** [comment]
добавил функции норм сохранения и теперь можно рассчитать еще раз, заполняються формы даееыми, введенными в прошлый раз

**Comment by ArtemSherenkovskiy** [comment]
работают только сервис горячей и холодной воды
